spring.application.name=perfex_sb
server.port=9090
spring.datasource.url=jdbc:postgresql://103.39.132.39:5432/PERFEXPGSBDEV
spring.datasource.username=campuser
spring.datasource.password=campusr_!234

 spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=validate
# spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# HikariCP connection pool settings
spring.datasource.hikari.maximum-pool-size=20    
spring.datasource.hikari.minimum-idle=5           
spring.datasource.hikari.idle-timeout=30000      
spring.datasource.hikari.connection-timeout=20000 
spring.datasource.hikari.max-lifetime=1800000  

# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.show-sql=false
# spring.jpa.open-in-view=false
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.jpa.properties.hibernate.jdbc.fetch_size=1000
spring.jpa.properties.hibernate.default_batch_fetch_size=1000

