package com.akranta.perfex_sb.service;

import com.akranta.perfex_sb.config.TerminalBrowserCookieProperties;

import jakarta.servlet.http.Cookie;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

import org.springframework.http.HttpHeaders;
import org.springframework.http.ResponseCookie;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.util.Optional;
import java.util.regex.Pattern;

/**
 * Creates, reads, renews and deletes the Perfex terminal-browser cookie.
 *
 * The cookie value is the raw 256-bit random token generated by:
 *
 * TerminalTokenGenerator.generateBrowserToken()
 *
 * PostgreSQL stores only:
 *
 * SHA-256(raw token)
 */
@Service
public class TerminalBrowserCookieService {

    /*
     * TerminalTokenGenerator produces:
     *
     * 32 random bytes
     * Base64 URL encoding without padding
     * exactly 43 URL-safe characters
     */
    private static final Pattern RAW_TOKEN_PATTERN = Pattern.compile(
            "^[A-Za-z0-9_-]{43}$");

    private final TerminalBrowserCookieProperties cookieProperties;

    public TerminalBrowserCookieService(
            TerminalBrowserCookieProperties cookieProperties) {

        this.cookieProperties = cookieProperties;
    }

    /**
     * Sends a newly generated browser token to the browser.
     *
     * Call this only after the related token hash has been saved
     * successfully in the database.
     */
    public void writeBrowserCookie(
            HttpServletResponse response,
            String rawBrowserToken) {

        requireResponse(response);

        validateRawToken(rawBrowserToken);

        ResponseCookie responseCookie = buildPersistentCookie(
                rawBrowserToken);

        addCookieHeader(
                response,
                responseCookie);
    }

    /**
     * Reissues an already validated token with a fresh Max-Age.
     *
     * This does not generate or rotate the token.
     *
     * The future terminal-profile service should call this only after:
     *
     * 1. reading the token;
     * 2. hashing it;
     * 3. confirming an ACTIVE database binding;
     * 4. deciding that renewal is required.
     */
    public void renewBrowserCookie(
            HttpServletResponse response,
            String validatedRawBrowserToken) {

        writeBrowserCookie(
                response,
                validatedRawBrowserToken);
    }

    /**
     * Reads the configured terminal cookie from the incoming request.
     *
     * Invalid or ambiguous client cookie values are treated as absent.
     * They do not produce a server exception.
     */
    public Optional<String> readBrowserToken(
            HttpServletRequest request) {

        if (request == null) {
            return Optional.empty();
        }

        Cookie[] cookies = request.getCookies();

        if (cookies == null
                || cookies.length == 0) {
            return Optional.empty();
        }

        String cookieName = cookieProperties.getName();

        String matchedToken = null;

        for (Cookie cookie : cookies) {

            if (cookie == null) {
                continue;
            }

            if (!cookieName.equals(
                    cookie.getName())) {
                continue;
            }

            String candidateToken = cookie.getValue();

            if (!isValidRawToken(
                    candidateToken)) {
                /*
                 * A malformed terminal cookie should never be used
                 * for a database lookup.
                 */
                return Optional.empty();
            }

            if (matchedToken != null
                    && !matchedToken.equals(
                            candidateToken)) {
                /*
                 * Two cookies with the same name but different values
                 * would create an ambiguous identity.
                 */
                return Optional.empty();
            }

            matchedToken = candidateToken;
        }

        return Optional.ofNullable(
                matchedToken);
    }

    public boolean hasValidBrowserCookie(
            HttpServletRequest request) {

        return readBrowserToken(request)
                .isPresent();
    }

    /**
     * Instructs the browser to delete the terminal cookie.
     *
     * Name and path must match the original cookie.
     */
    public void deleteBrowserCookie(
            HttpServletResponse response) {

        requireResponse(response);

        ResponseCookie expiredCookie = ResponseCookie
                .from(
                        cookieProperties
                                .getName(),
                        "")
                .httpOnly(
                        cookieProperties
                                .isHttpOnly())
                .secure(
                        cookieProperties
                                .isSecure())
                .sameSite(
                        cookieProperties
                                .getSameSite())
                .path(
                        cookieProperties
                                .getPath())
                .maxAge(
                        Duration.ZERO)
                .build();

        addCookieHeader(
                response,
                expiredCookie);
    }

    public String getCookieName() {
        return cookieProperties.getName();
    }

    private ResponseCookie buildPersistentCookie(
            String rawBrowserToken) {

        return ResponseCookie
                .from(
                        cookieProperties
                                .getName(),
                        rawBrowserToken)
                .httpOnly(
                        cookieProperties
                                .isHttpOnly())
                .secure(
                        cookieProperties
                                .isSecure())
                .sameSite(
                        cookieProperties
                                .getSameSite())
                .path(
                        cookieProperties
                                .getPath())
                .maxAge(
                        cookieProperties
                                .getMaxAge())
                /*
                 * Domain is intentionally omitted.
                 *
                 * This keeps the cookie host-only and is required when
                 * using the __Host- prefix in production.
                 */
                .build();
    }

    private static void addCookieHeader(
            HttpServletResponse response,
            ResponseCookie responseCookie) {

        /*
         * addHeader is used instead of setHeader because another
         * operation may already have added a different Set-Cookie header.
         */
        response.addHeader(
                HttpHeaders.SET_COOKIE,
                responseCookie.toString());
    }

    private static void validateRawToken(
            String rawBrowserToken) {

        if (!isValidRawToken(
                rawBrowserToken)) {
            throw new IllegalArgumentException(
                    "Browser token must contain exactly "
                            + "43 URL-safe characters.");
        }
    }

    private static boolean isValidRawToken(
            String rawBrowserToken) {

        return rawBrowserToken != null
                && RAW_TOKEN_PATTERN
                        .matcher(rawBrowserToken)
                        .matches();
    }

    private static void requireResponse(
            HttpServletResponse response) {

        if (response == null) {
            throw new IllegalArgumentException(
                    "HTTP response is required.");
        }
    }
}